config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  #devise_for :admin_users, ActiveAdmin::Devise.config
  get 'pages/index'
  devise_for :users
  root 'tweets#index'
  resources :tweets do
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet'
  end

  get "tweets(?search=:search)", to:'tweets#search', as:'search' 
  get 'api/news', to: 'apis#rescue_latest_tweets'
  get 'api/:from/:to', to: 'apis#rescue_last_dates'
  
  post 'api/tweets', to: 'apis#tweet_with_postman'

  resources :retweets
  resources :likes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
	has_many :likes
	has_many :retweets
	validates :content, presence: true 
	enum status: [:draft, :published]
	paginates_per 50
	scope :tweets_for_me, -> (ids){where(user_id: ids)} 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :set_current_tweet, only: [:likes, :retweet]

  def index

    if !current_user

      @q=Tweet.ransack(params[:q])
      @tweets=@q.result.order('created_at DESC').page params[:page]
      @retweets=Retweet.all 

    else
      @q=Tweet.tweets_for_me(current_user.followings.pluck(:id)).ransack(params[:q])
      @tweets=@q.result.order('created_at DESC').page params[:page] 
      @retweets=Retweet.retweets_for_me(current_user.followings.pluck(:id)).order('created_at DESC').page params[:page]
      @tweet=Tweet.new  
    end

  end

  def show
    @likes = Like.all 
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      redirect_to root_path
    else
      render 'new'
    end 
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def likes
    if @tweet.is_liked?(current_user)
      @tweet.remove_like(current_user)

    else
      @tweet.add_like(current_user)

    end 
    redirect_to root_path
  end

  def search
    @q=Tweet.ransack(content_cont_any: params[:search])
    @tweets=@q.result
  end 

  def retweet
    new_tweet = Tweet.create(content: @tweet.content, user: current_user, rt_ref:@tweet.id)
    redirect_to root_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def set_current_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user)
    end
  
  def organized_pages
    @tweets = Tweet.order(:created_at).page params[:page]
  end  

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  
  <div class="field">
    <%= form.label :content, "#{current_user.name} dice:" %>
    <%= form.text_area :content, id: :tweet_content, :class => "form-control" %>
  </div>

  <%= form.hidden_field :user_id, :value => current_user.id %> 
  
  <div class="actions text-right my-2">
    <%= form.submit "Guardar", :class => " btn btn-primary" %>
  </div>

<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Tweets</h1>

<% if current_user %>   
  <%= render 'form', tweet: @tweet %>
<% end %>

<%= search_form_for @q, method: :get ,url: root_path do |f| %>
  <%= f.label :content_cont %>
  <%= f.search_field :content_cont %>
  <%= f.submit 'buscar'%>
<%end %>

<table>
  <thead>
    <tr>
      <th>Contenido</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%=image_tag tweet.user.image_url, class: "images_avatar rounded-circle border border-info " %></td>  
        <td><%= tweet.user.name %></td>
        <td><%= link_to time_ago_in_words(tweet.created_at) , tweet%></td> 
        <td><% @content = tweet.content %>
        <% @content = @content.split(" ") %>
          <% @newcontent = @content.each do |item| %>
            <% if item.include?("#") %>
              <%=item = link_to item, search_path(search: item.gsub('#','')) %>
            <% else %>
              <%=item%> 
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Ver', tweet %></td>
        <td><%= link_to 'Editar', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Eliminar', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <td>
          <%=tweet.likes_count%>
          <%= link_to 'like', likes_path(tweet.id), method: :post, class: "fas fa-heart"%>
        </td>

        <td>
          <%=tweet.retweets_count%>
          <%= link_to 'retweet', retweets_path(tweet.id), method: :post, class: "fas fa-retweet"%> 
        </td>
      </tr>
    <% end %>
  </tbody>

  <tbody>
    <% @retweets.each do |retweet| %>
    <tr>
      <td><%=image_tag retweet.user.image_url, class: "images_avatar rounded-circle border border-info " %></td>  
      <td><%= retweet.user.name %></td>
      <td><%=image_tag retweet.tweet.user.image_url, class: "images_avatar rounded-circle border border-info " %></td>  
      <td><%= retweet.tweet.user.name %></td>
      <td><a href=<%=tweets_path(retweet.tweet_id)%>> <%= time_ago_in_words(retweet.tweet.created_at) %></a></td> 
      <td><%= retweet.tweet.content %></td>
    
      <td>
        <%=retweet.tweet.likes_count%>
        <%= link_to 'like', likes_path(retweet.tweet.id), method: :post, class: "fas fa-heart"%>
      </td>

      <td>
        <%=retweet.tweet.retweets_count%>
        <%= link_to 'retweet', retweets_path(retweet.tweet.id), method: :post, class: "fas fa-retweet"%> 
      </td>
    </tr>

  <% end %>

</tbody>

</table>

<br>

<%= link_to 'Nuevo Tweet', new_tweet_path %>
<%= paginate @tweets %>

app/views/tweets/new.html.erb
<h1>Nuevo Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/search.html.erb
<tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%=image_tag tweet.user.image_url, class: "images_avatar rounded-circle border border-info " %></td>  
        <td><%= tweet.user.name %></td>
        <td><%= link_to time_ago_in_words(tweet.created_at) , tweet%></td> 
        <td><% @content=tweet.content %>
            <% @content=@content.split(" ") %>
            <% @newcontent=@content.each do |item| %>
              <% if item.include?("#") %>
                <%=item=link_to item, search_path(search: item.gsub('#','')) %>
              <% else %>
                <%=item%> 
              <% end %>
            <% end %>
        </td>
        <td><%= link_to 'Ver', tweet %></td>
        <td><%= link_to 'Editar', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Eliminar', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <td>
          <%=tweet.likes_count%>
          <%= link_to 'like', likes_path(tweet.id), method: :post, class: "fas fa-heart"%>
        </td>

        <td>
          <%=tweet.retweets_count%>
          <%= link_to 'retweet', retweets_path(tweet.id), method: :post, class: "fas fa-retweet"%> 
        </td>
      </tr>
    <% end %>
  </tbody>

app/views/tweets/show.html.erb
<div class= "row">
  <div class= "col-12  shadow-lg rounded  p-1 mt-3 card">
    <div class="row">
              
      <div class="col-9 "> 
        <span class="username"><%= @tweet.user.name%> dice: </span></br/>   
        <span><%=link_to '<i class="far fa-calendar-alt"></i>'.html_safe+distance_of_time_in_words(Time.now, @tweet.created_at), @tweet%></span></br/>
        <%= @tweet.content%>
      </div>

      <div class= "col-12">

        <% @likes.each do |like| %>
          <% if @tweet.id==like.tweet_id %>

            <%=image_tag like.user.image_url, class: "images_avatar rounded-circle border border-info " %>

          <% end %>
        <% end %>

      </div>
    </div>
  </div>

</div>

<%= link_to 'Back', tweets_path %>